version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: innovation-hub
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - '5050:80'
    volumes:
      - ./.docker/data/pgadmin:/var/lib/pgadmin
      - type: bind
        source: ./.docker/config/pgadmin/servers.json
        target: /pgadmin4/servers.json
